### ISSUE TITLE
Carbonated Wishlist

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbonated#2]
Carbonated is an internal tooling project for the Carbon Design System. It will eventually be composed of the following service areas:

- Adoption: track adoption-related KPIs and provide insights into performance
- Audits: research usability of components in the system
- Automation: typically done through GitHub bots. Provides attempts at automation where appropriate in our process
- Management: ability to manage team and repo settings across the ecosystem
- Support: help carbon developers better service users on GitHub and Slack

---

- Support
  - Review queue for PRs, similar to: https://buildbot2.rust-lang.org/homu/queue/rust
  - Issue triage view
    - View issues that have not been responded to yet
    - View issues that have not been triaged yet
  - PR triage view
    - View PRs for me to review
  - View stale issues/PRs
- Management
  - Team
    - Manage roster of employees through GitHub
      - Automatically add to appropriate teams and repos
  - Repositories
    - Add ability to sync GitHub settings between repos we manage
      - Issue labels
      - Milestones
      - Branch permissions
  - CircleCI
    - Add ability to sync CircleCI settings and tokens between repos we manage
- Automation
  - Bots
    - GitHub
      - Automatically respond to first-time contributors with link to CLA
      - Close stale issues and pull requests
      - Automatically merge in approved PRs
      - Automatically label PRs based on status checks
    - Slack
      - Automatically make issue from channel
	  - Use key words to properly direct folks towards the right channel
- Audits
  - Usability
  - Accessibility

**Comment by joshblack** [comment]
Routes:

```
# Home
/

# Authorization
/login
/auth/github
/auth/github/callback

# Manage
/manage
/manage/team
/manage/projects
/manage/projects/:name
/manage/projects/:name/repos
/manage/projects/:name/ci

# Support
/support
/support/review
/support/triage

# Studies
/studies
/studies/new
/studies/:study
/invite

# Audits
/audits
/audits/:audit
/audits/:audit/invite

# Bots
/bots/github/webhook
/bots/slack/webhook

# Adoption
/adoption
/adoption/:org
/adoption/:org/:portfolio
/adoption/:org/:portfolio/:offering
```

**Comment by joshblack** [comment]
Ideas:

- interactive style explorer to help design figure out where colors, type, motion values are defined in our styles
- Slack bot to capture questions
- Tool for sending out surveys and seeing results
- Tool for visualizing github issue and PR activity (good dogfood of data viz)
- Link shorterner/obscurer at link.carbondesignsystem.com
- Web page where users can vote on what to prioritize
- reply with message when `@here` is used
- Automatically test projects that adopters have listed when a new release is published
- Feature voting, vote sharing based on stakeholders and contributions, more points per contributors for focus, our roadmap is partially dedicated to features in this list

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/52918765-65878280-32c0-11e9-8712-8f27fc94058f.png)

Carbon bot marks issues as stale, contribs can mark as not stale, closes automatically after 30days

**Comment by joshblack** [comment]
Initial architecture diagram:

![image](https://user-images.githubusercontent.com/3901764/53750161-ae1d6f00-3e6e-11e9-81cd-4199b6f6dbe5.png)

[Link](https://dreampuf.github.io/GraphvizOnline/#%2F%2F%20https%3A%2F%2Farticles.microservices.com%2Fan-alternative-way-of-visualizing-microservice-architecture-837cbee575c1%0A%2F%2F%20https%3A%2F%2Fgist.github.com%2Fvladgolubev%2F80c5523336ddec3859c0e90d9a070882%0Adigraph%20architecture%20%7B%0A%20%20rankdir%3DLR%3B%0A%20%20%0A%20%20%2F%2F%20Client-side%20Apps%20-%20%23FFEB3B%20(yellow)%0A%20%20node%5Bfillcolor%3D%22%23FFEB3B%22%20style%3D%22filled%22%20fontcolor%3D%22black%22%5D%3B%0A%20%20front_end%5Blabel%3D%22UI%22%5D%0A%20%20%0A%20%20%2F%2F%20API%20Gateways%20-%20%23FFCCBC%20(light%20orange)%0A%20%20node%5Bfillcolor%3D%22%23FFCCBC%22%20style%3D%22filled%22%20fontcolor%3D%22black%22%5D%3B%20%20%0A%20%20node_api%5Blabel%3D%22Node.js%22%5D%0A%20%20%0A%20%20%2F%2F%203rd-party%20APIs%20-%20%23CFD8DC%20(light%20grey)%0A%20%20node%5Bfillcolor%3D%22%23CFD8DC%22%20style%3D%22filled%22%20fontcolor%3D%22black%22%5D%3B%0A%20%20github%3B%0A%20%20%0A%20%20%2F%2F%20Storage%20-%20%23303F9F%20(dark%20blue)%0A%20%20node%5Bfillcolor%3D%22%23303F9F%22%20style%3D%22filled%22%20fontcolor%3D%22white%22%5D%3B%0A%20%20redis%3B%20postgres%3B%0A%20%20%0A%20%2F%2F%20Handlers%20-%20%23C8E6C9%20(light%20green)%0A%20%20node%5Bfillcolor%3D%22%23C8E6C9%22%20style%3D%22filled%22%20fontcolor%3D%22black%22%5D%3B%0A%20%20session%3B%20graphql%3B%20oauth%3B%20assets%3B%20health%3B%0A%20%20%0A%20%20subgraph%20client%20%7B%0A%20%20%20%20%20%20front_end%20-%3E%20%7Bnode_api%7D%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20gateways%20%7B%0A%20%20%20%20%20%20node_api%20-%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20assets%2C%0A%20%20%20%20%20%20%20%20%20%20graphql%2C%0A%20%20%20%20%20%20%20%20%20%20health%2C%0A%20%20%20%20%20%20%20%20%20%20oauth%2C%0A%20%20%20%20%20%20%20%20%20%20session%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20handlers%20%7B%0A%20%20%20%20%20%20session%20-%3E%20%7Bredis%7D%0A%20%20%20%20%20%20graphql%20-%3E%20%7Bpostgres%7D%0A%20%20%20%20%20%20health%20-%3E%20%7Bredis%2C%20postgres%2C%20github%7D%0A%20%20%20%20%20%20oauth%20-%3E%20%7Bgithub%2C%20postgres%7D%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20clients%20%7B%0A%20%20%20%20%20%20github%0A%20%20%7D%0A%20%20%0A%20%20subgraph%20storage%20%7B%0A%20%20%20%20%20%20postgres%0A%20%20%20%20%20%20redis%0A%20%20%7D%0A%7D)

**Comment by vpicone** [comment]
Are we still testing out stale bot? Would be awesome to start culling the backfield.
